name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # https://github.com/marketplace/actions/ssh-deploy
      - name: Deploy To Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "start-site/target/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_JAR_TARGET }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: /root/start/taotao-cloud-start.sh restart

#      - name: set ssh key # 临时设置 ssh key
#        run: |
#          mkdir -p ~/.ssh/
#          echo "${{secrets.COSEN_ID_RSA}}" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          ssh-keyscan "106.xx.xx.xx" >> ~/.ssh/known_hosts
#
#      - name: deploy
#        run: |
#          ssh work@106.xx.xx.xx "
#          cd /home/work/choba-lego/admin-fe;
#          git remote add origin https://Cosen95:${{secrets.COSEN_TOKEN}}@github.com/Choba-lego/admin-fe.git;
#          git checkout feature_dev;
#          git config pull.rebase false;
#          git pull origin feature_dev;
#          git remote remove origin;
#
#          # 构建 prd-dev
#          # npm i;
#          # npm run build-dev;
#
#          # 启动 docker
#          docker-compose build admin-fe; # 和 docker-compose.yml service 名字一致
#          docker-compose up -d;
#          "
#      - name: delete ssh key
#        run: rm -rf ~/.ssh/id_rsa
